### ISSUE TITLE
Display of PrincipalPubl info

### ISSUE THREAD

**Issue by rla2118** [paregorios/dclpxsltbox#14]
Publication info is absent from HTML (see, e.g.,  https://dclp.github.io/dclpxsltbox/output/dclp/129/128967.html).  Please add it, drawing on (https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128967.xml#l99)

I would suggest an HTML display similar to what we get in HGV.  In the case of the above papyrus, it would look like: P.Oxy. 75 5040  
Also, I think it should appear at or near the top of the metadata, perhaps just below Work?

**Comment by paregorios** [comment]
@cgajjar05 please investigate why the ```<div type="bibliography" subtype="principalEdition">``` in the referenced XML file is not getting picked up by the XSLT transform.

**Comment by paregorios** [comment]
This is probably just an example of what we aimed to resolve with #109. @cgajjar05 please address #109 (which is now unblocked) and then circle back to this ticket to make sure it is resolved.

**Comment by paregorios** [comment]
Transferred to https://github.com/DCLP/dclpxsltbox/issues/123
